config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
     member do
      patch :complete
     end
   end
 end
  root "todo_lists#index"
  get '/todo_listas' => 'todo_lists#indexlists'
  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  def completed?
    !completed_at.blank?
   end

   def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, :dependent => :destroy
    belongs_to :user


    

def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |items|
        csv << items.attributes.values_at(*column_names)
      end
    end
  end
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :todo_lists

         def view
          @user=current_user
        end
        def edit
          @user=current_user
        end
        # styles: { medium: "1100x1100>", thumb: "1100x1100>" },  :style
        has_attached_file :avatar, default_url: "/images/thumb/missing.png"
         validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :is_female, :date_of_birth, :description, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :is_female, :date_of_birth, :description, :avatar])
 
 
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
    before_action :set_todo_list
    before_action :set_todo_item, except: [:create]

    

    
    def create
        @todo_item = @todo_list.todo_items.create(todo_item_params)
        redirect_to @todo_list
    end
    def destroy
        @todo_item = @todo_list.todo_items.find(params[:id])
        if @todo_item.destroy
            flash[:success] = "Todo List item was deleted."
        else
            flash[:error] = "Todo List item could not be deleted."
        end
        redirect_to @todo_list 
    end
    def complete
        @todo_item.update_attribute(:completed_at, Time.now)
        redirect_to @todo_list, notice: "Todo item completed"
    end

    private
    def set_todo_list
        @todo_list = TodoList.find(params[:todo_list_id])
    end

    def todo_item_params
        params[:todo_item].permit(:content)
    end
    def set_todo_item
        @todo_item = @todo_list.todo_items.find(params[:id])
    end
    

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  

 
 def indexlists
  
  @user=current_user
  #HardWorker.perform_async()
  #@todo_lists = TodoList.all
  @todo_lists = @user.todo_lists
  respond_to do |format|
    format.html
    format.csv { send_data @todo_lists.to_csv }
    format.pdf do 
      pdf = ListPdf.new(@user)
      send_data pdf.render, filename: "Tus listas.pdf",
                            type: "application/pdf",
                            disposition: "inline"

      
    end
  end



end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
    @user=current_user
    @todo_lists = @user.todo_lists
    @todo_item = current_user.todo_lists
    respond_to do |format|
      format.html
      format.csv { send_data @todo_list.todo_items.to_csv }
      format.pdf do 
        pdf = ItemPdf.new(@todo_list)
        send_data pdf.render, filename: "Tus Tareas.pdf",
                              type: "application/pdf",
                              disposition: "inline"
  
        
      end
    end
    
    #@todo_lists = curent_user.todo_lists
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user_id = current_user.id
    @user = current_user

    respond_to do |format|
      if @todo_list.save
        #WeeklyMailer.sample_email(@user).deliver
        #SendEmailJob.set(wait: 1.seconds).perform_later(@user)
        #SendEmailJob.set(wait: 1.seconds).perform_later(@user)
        

        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>

    
<meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">ToDo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
    <% if user_signed_in? %>
      <a class="nav-item nav-link"><%= link_to 'Inicio', todo_lists_path %></a>
      <a class="nav-item nav-link"><%= link_to "Editar perfil", edit_user_registration_path %></a>
      <a class="nav-item nav-link"> <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %></a>
      <% else %>
      <a class="nav-item nav-link"><%= link_to 'Inicio', todo_lists_path %></a>
      <a class="nav-item nav-link"><%= link_to "Iniciar sesion", new_user_session_path %></a>
      <a class="nav-item nav-link"><%= link_to "Registrate", new_user_registration_path %></a>
      <% end %>
    </div>
  </div>
</nav>
      
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "Nueva Tarea" %>
 <%= f.submit "Crear" %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="container">
<div class="row">
<div class="col-md-12" align="center">
<!--<div class="row clearfix">-->
 <% if todo_item.completed? %>

  <div class="todo_item">
   <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
  </div>
    <div class="complete">
  <!-- <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
  </div>-->
  <div class="trash">
   <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
  <br>
 <% else %>
  
  <div class="todo_item">
   <p><%= todo_item.content %></p>
  <!--</div>-->
  <!--<div class="complete">-->
   <%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
 <!-- </div>-->
  <!--<div class="trash">-->
   <%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
  <br>
 <% end %>
<!--</div>-->
</div>
</div>
</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Titulo" %>
    <%= form.text_field :title, id: :todo_list_title %>
  </div>

  <div class="field">
    <%= form.label :description, "Descripcion" %>
    <%= form.text_area :description, id: :todo_list_description %>
  </div>
  <!--
  <div class="actions">
    <%= form.submit%>
  </div>
  -->
  </br>
  <button type="submit" class="btn btn-primary actions">Actualizar</button>
<% end %>

app/views/todo_lists/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-12" align="center">
<h1>Editar Lista de tareas Chida</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Mostrar', @todo_list %> |
<%= link_to 'Regresar', todo_listas_path %>
</div>
</div>
</div>

app/views/todo_lists/index.html.erb
<div class="container">

<div class="row">
<div class="col-md-12 col-sm-12" align="center">
<br>
<% if user_signed_in? %>
    <h1>BIENVENIDO COMPA</h1>
    <%= link_to 'Mostrar mis listas', :action => :indexlists %>
    
    
    <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
    <%= link_to "Edita tu info ", edit_user_registration_path %>
<% else %>
<h1>ACCEDE PARA MAS OPCIONES</h1>
    <%= link_to "Iniciar sesion", new_user_session_path %>
    <%= link_to "Crear cuenta", new_user_registration_path %>
<% end %>


</div>
</div>
</div>

app/views/todo_lists/indexlists.html.erb
<div class="container">
<div class="row">
<div class="col-md-12" align="center">
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% if user_signed_in? %>
    <% @todo_lists.each do |todo_list| %>
  
      <tr>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
      </tr>
      
      <tr>
        <td><%= link_to 'Mostrar', todo_list %></td>
        <td><%= link_to 'Editar', edit_todo_list_path(todo_list) %></td>
     <td><%= link_to 'Eliminar', todo_list, method: :delete, data: { confirm: 'Estas seguro de borrar esta listaaaaa??????' } %></td>
      <!--  <td><%= link_to 'Regresar', todo_lists_path %></td> -->
      <!--  <td><%= link_to 'Nueva Lista', new_todo_list_path %></td> -->
      </tr>
      <tr>
      <td> </br> </br></td>
      </tr>
  
      <%  end %>
      
    <% end %>
  </tbody>
  
</table>
<%= link_to 'Regresar', todo_lists_path %>
       <%= link_to 'Nueva Lista', new_todo_list_path %>
       

<p>
  Download:
  <%= link_to "CSV", todo_listas_path(format: "csv") %> 
    <%= link_to "PDF", todo_listas_path(@todo_lists, format: "pdf") %> 
</p>


</div>
</div>
</div>

app/views/todo_lists/new.html.erb
<div class="container">
<div class="row">
<div class="col-md-12" align="center">
<h1>Nueva Lista ToDo</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Regresar', todo_lists_path %>
</div>
</div>
</div>

app/views/todo_lists/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-12" align="center">

<!--<p id="notice"><%= notice %></p>-->

<p>
  <strong>Titulo:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @todo_list.description %>
</p>

<div id="todo_items_wrapper">
 <%= render @todo_list.todo_items %>
 <div id="form">
  <%= render "todo_items/form" %>
 </div>
</div>


<%= link_to 'Editar', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Regresar', todo_listas_path %>|
<%= link_to 'Eliminar', todo_list_path(@todo_list), method: :delete, data: { confirm: "Estas seguro de eliminar esta lista?" } %> |
<p>
  Download:
  <%= link_to "CSV", todo_list_path(@todo_list ,format: "csv") %> 
  <%= link_to "PDF", todo_list_path(@todo_list,format: "pdf") %> 
</p>

</div>
</div>
</div>